module.exports = {
    apps: [{
        name: "lantu-server",
        script: "./app.js",
        instances: 4,
        exec_mode: 'cluster',
        env_production: {
            CHROME_EXECUTEABLE_PATH: '/opt/google/chrome/chrome',
            NODE_ENV: "production",
            WECHAT_APPID: "wx452daef92362cc61",
            WECHAT_APPSECRET: "81805784e8898f4b6d488c56908624de",
            MONGO_URI: "mongodb://lantu:admin1q2w3e4R@lantubaba.mongodb.zhangbei.rds.aliyuncs.com:3717,dds-8vb0b8dcbe26b0c42.mongodb.zhangbei.rds.aliyuncs.com:3717/lantu",
            REPLICA_SET: 'mgset-500121724',
            DATA_BASE_NAME: 'lantu',
            APP_ID: "lantu-server",
            APP_NAME: "蓝图巴巴",
            SSL_FORCE: true,
            SERVER_DOMAIN: "service.lantubaba.com",
            SERVER_PORT: "80",
            SERVER_NAME: "api",
            MASTER_KEY: "admin1q2w3e4R",
            SMTP_USER: "system@staror.cn",
            SMTP_PASSWORD: "admin1q2w3e4R",
            SMTP_HOST: "smtp.qiye.163.com",
            SMTP_PORT: "25",
            MANAGER_USER: "scaperow",
            MANAGER_PASSWORD: "scape890315",
            COMPANY_NAME: "星系软件工作室",
            COMPANY_SHORT_NAME: "星系软件",
            CLIENT_URL: "http://www.lantubaba.com/",
            OSS_REGION: 'oss-cn-zhangjiakou',
            OSS_KEY: 'LTAIjDh79ObKn8gX',
            OSS_SECRET: 'WWx8w66J8WB0AIYwDpeDTrn54Ayswq',
            BUCKET: 'lantubaba',

            ALIPAY_APP_ID: '2019122360214280',
            ALIPAY_NOTIFY_URL: 'https://service.lantubaba.com/notify/alipay',
            ALIPAY_KEY: 'maUtc0xqOjt9vJL5+7u6aA==',
            ALIPAY_RSA_PRIVATE: '/etc/ssh/alipay.ppk',
            ALIPAY_RSA_PUBLIC: '/etc/ssh/alipay_center.pub',
            ALIPAY_TIMEOUT: '30m',
            ALIPAY_URL: 'https://openapi.alipay.com/gateway.do',
            ALIPAY_RETURN_URL: 'https://www.lantubaba.com/#/notify/alipay/#/notify/alipay',

            WEPAY_NOTIFY_URL: 'http://124.115.115.110:5000/notify/wepay',
            WEPAY_KEY: '58F53BC186257F3732DEC7FC8AA4150996B395AA',
            WEPAY_MECH_ID: '1571825771',
            WEPAY_APP_ID: 'wxf3a7de1532609abc',
            WEPAY_CERTIFICATE: '/Users/Ben/.ssh/wepay.p12',
        }
    }]
}